# Changes here will be overwritten by Copier.
# This file stores the template source, commit, and answers used by copier update.

_commit: v0.1.0
_src_path: gh:Nikitid/project-template
author_name: Nikitid
license_type: MIT
main_language: python
project_description: Automated Python script for merging MKV video with dubbed audio
project_name: MKV auto merger
use_devcontainer: true
use_docker: false
use_github_actions: true
use_vscode: true
