# Changes here will be overwritten by Copier.
# This file stores the template source, commit, and answers used by copier update.

_commit: v0.1.0
_src_path: /Users/nikitid/Developer/projects/project-template
author_name: Nikitid
license_type: MIT
main_language: python
project_description: Prepare anime and TV series folders from trackers for Jellyfin.
project_name: MKV Auto Merger
use_devcontainer: false
use_docker: false
use_github_actions: true
use_vscode: false
